default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USER") %>
  password: <%= ENV.fetch("RAILS_DB_PASS") %>
  host: <%= ENV.fetch("RAILS_DB_HOST") %>

development:
  <<: *default
  database: balance_api_development
test:
  <<: *default
  database: balance_api_test
production:
  <<: *default
  database: balance_api_production
